import type { Metadata } from "next";
import "./globals.css";
import Navbar from "./components/navbar/page";
import Footer from "./components/footer/page";
import { url } from "inspector";



export const metadata: Metadata = {
  title: "CG HEVEN",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className=' bg-slate-950  ' 
      >
        {/* <Navbar/> */}
        
        {children}
        {/* <Footer/> */}
      </body>
    </html>
  );
}
